# Generated by Django 4.2.15 on 2024-09-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_view_employee', 'Can view employee')]},
        ),
    ]
